language: java
sudo: false
jdk:
- openjdk8
before_script:
- rm -rf target
env:
  global:
  - TERM=dumb
  - MALLOC_ARENA_MAX=1
  - GRADLE_OPTS="-Xmx768m -Xms256m -XX:MaxPermSize=372m -XX:+CMSClassUnloadingEnabled"
  - GIT_NAME="Graeme Rocher"
  - GIT_EMAIL="graeme.rocher@gmail.com"
install: "/bin/true"
script:
- "./travis-build.sh"
after_deploy:
- "./gradlew sdkMajorRelease"
cache:
  directories:
  - "$HOME/.gradle"